spring.application.name=docushield-api

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/docushield
spring.datasource.username=postgres
spring.datasource.password=Misthi@19

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Server
server.port=8080
